name = "counter-visits"
main = "src/index.ts"
compatibility_date = "2024-04-02"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "kv", id = "dfeedf71007c47a4ba30d496393fcdc2" }
]

[placement]
mode = "smart"